#pragma once

#define MALONECANGJIE_VERSION_MAJOR 1
#define MALONECANGJIE_VERSION_MINOR 0
#define MALONECANGJIE_VERSION_PATCH 0
#define MALONECANGJIE_VERSION_BUILD 0

#define MALONECANGJIE_FILE_VERSION \
    MALONECANGJIE_VERSION_MAJOR, \
    MALONECANGJIE_VERSION_MINOR, \
    MALONECANGJIE_VERSION_PATCH, \
    MALONECANGJIE_VERSION_BUILD

#define MALONECANGJIE_PRODUCT_VERSION MALONECANGJIE_FILE_VERSION

#define MALONECANGJIE_FILE_VERSION_STRING "1.0.0.0"
#define MALONECANGJIE_PRODUCT_VERSION_STRING MALONECANGJIE_FILE_VERSION_STRING
